inherit_from:
  - .rubocop_airbnb.yml

Metrics/LineLength:
  Max: 130

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - !ruby/regexp /config\/(?!routes.rb).*$/
